"""events table

Revision ID: 65f07cd4a3b9
Revises: 70ef308a1473
Create Date: 2020-06-28 13:08:04.190500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f07cd4a3b9'
down_revision = '70ef308a1473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupid', sa.Integer(), nullable=True),
    sa.Column('allDay', sa.Boolean(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('groupid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
